package lan.citadel.device_gateway;

public enum Meter {
    CONNECT_TV_SUCCESS_COUNT,
    CONNECT_TV_FAILURE_COUNT,

    DISCONNECT_TV_SUCCESS_COUNT,
    DISCONNECT_TV_FAILURE_COUNT,

    RETRIEVE_TV_APPS_DURATION,
    OPEN_TV_APP_DURATION,
    SEND_TV_KEY_DURATION,
}
